// =============================================================================
// FILE: src/hooks/useFloatingAlerts.ts
// =============================================================================
// PURPOSE: Custom hook and context for managing floating toast notifications.
//
// This file defines:
//   - AlertNotification interface (shape of a toast notification)
//   - FloatingAlertContext (React context for notification state)
//   - useFloatingAlerts hook (consumes the context)
//
// The actual provider implementation (FloatingAlertProvider) and
// UI rendering (FloatingAlertContainer) are in the FloatingAlert.tsx component.
//
// NOTIFICATION TYPES:
//   - "warning": Amber/orange styling for threshold warnings
//   - "critical": Red styling for critical threshold breaches
//
// USAGE:
//   const { addNotification, removeNotification } = useFloatingAlerts();
//   addNotification({ message: "High temperature!", type: "critical", ... });
// =============================================================================

import { createContext, useContext } from "react";

/**
 * Represents a single floating alert notification.
 * Each notification has a unique ID, message, severity type, and sensor details.
 */
interface AlertNotification {
  id: string;              // Unique identifier (generated by provider)
  message: string;         // Display text for the notification
  type: "warning" | "critical";  // Severity level for styling
  parameter: string;       // Sensor key (e.g., "temperature", "device")
  value: number;           // Current sensor reading value
  threshold: "min" | "max";      // Which threshold was breached
}

/**
 * Interface for the floating alert context value.
 * Provides methods to add, remove, and clear notifications.
 */
interface FloatingAlertContextType {
  notifications: AlertNotification[];
  addNotification: (notification: Omit<AlertNotification, "id">) => Promise<void>;
  removeNotification: (id: string) => void;
  clearNotifications: () => void;
}

// Create the context with null default. FloatingAlertProvider provides the actual value.
export const FloatingAlertContext = createContext<FloatingAlertContextType | null>(null);

/**
 * Custom hook to access floating alert notifications.
 * Must be used within a FloatingAlertProvider.
 * @returns Object with notifications array and manipulation methods
 */
export function useFloatingAlerts() {
  const context = useContext(FloatingAlertContext);
  if (!context) {
    throw new Error("useFloatingAlerts must be used within FloatingAlertProvider");
  }
  return context;
}

export type { AlertNotification, FloatingAlertContextType };
